### ISSUE TITLE
这个版本的内存占用如何

### ISSUE THREAD

**Issue by hinego** [AppleClash/clash-apple#1]
ios15以下有 15M内存限制 这个能跑起来吗？

跑起来大概占用多大内存？

速度如何

**Comment by Arror** [comment]
> ios15以下有 15M内存限制 这个能跑起来吗？
> 
> 跑起来大概占用多大内存？
> 
> 速度如何

跑不起来，编译不过。

Clash设置完配置后占用都20M+了。

准备先回退到go-tun2socks版本，这样iOS 15+暂时问题不大，然后转向leaf。

**Comment by hinego** [comment]
> 

你会rust吗

接rust准备怎么弄

go + rust混合？

还是纯 rust

我也有这块需求

**Comment by hinego** [comment]
`		_ = sys.Control(func(fd uintptr) {
			_ = syscall.SetsockoptInt(int(fd), syscall.SOL_SOCKET, syscall.SO_NO_CHECK, 1)
		})`

把 tcp.go 里面的这段删除试试 syscall.SO_NO_CHECK 这个unix 不支持

**Comment by hinego** [comment]
mac 就没有 SO_NO_CHECK

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setsockopt.2.html

**Comment by hinego** [comment]
纯go 版本tun2socks 内存占用太严重了。。。。还不如之前的cgo版本（即使没有维护更新了）

**Comment by Arror** [comment]
> 你会rust吗
> 
> 接rust准备怎么弄
> 
> go + rust混合？
> 
> 还是纯 rust
> 
> 我也有这块需求

Rust我不会😅，将leaf做为tun2socks理论上是可行的，目前来看是把leaf编译成静态库单独使用，把流量转发到clash的socks5代理。

你的需求也是在苹果平台上使用么？

**Comment by Arror** [comment]
> `_ = sys.Control(func(fd uintptr) { _ = syscall.SetsockoptInt(int(fd), syscall.SOL_SOCKET, syscall.SO_NO_CHECK, 1) })`
> 
> 把 tcp.go 里面的这段删除试试 syscall.SO_NO_CHECK 这个unix 不支持

我可以试试，但感觉大概率不可行，这个库是ClashForAndroid在用的。就算可行，估计和go-tun2socks差不多。

**Comment by Arror** [comment]
> 纯go 版本tun2socks 内存占用太严重了。。。。还不如之前的cgo版本（即使没有维护更新了）

确实，我试着用了一下，连接数量上来之后，立马达到NE内存限制，程序被强杀了。

**Comment by hinego** [comment]
> > `_ = sys.Control(func(fd uintptr) { _ = syscall.SetsockoptInt(int(fd), syscall.SOL_SOCKET, syscall.SO_NO_CHECK, 1) })`
> > 把 tcp.go 里面的这段删除试试 syscall.SO_NO_CHECK 这个unix 不支持
> 
> 我可以试试，但感觉大概率不可行，这个库是ClashForAndroid在用的。就算可行，估计和go-tun2socks差不多。

差别很大，go版本的tun2socks 里面用了很多gorotine 而且频繁创建[]byte

tun2socket这里它就一个64K的[]byte 持续复用

这里差别肯定有几十倍。。。

**Comment by hinego** [comment]
> > 你会rust吗
> > 接rust准备怎么弄
> > go + rust混合？
> > 还是纯 rust
> > 我也有这块需求
> 
> Rust我不会😅，将leaf做为tun2socks理论上是可行的，目前来看是把leaf编译成静态库单独使用，把流量转发到clash的socks5代理。
> 
> 你的需求也是在苹果平台上使用么？

是的 我也考虑过这么做 leaf 内存消耗 很少，我再mac上面测试 稳定7M

cgo版本 得30M左右
go版本 40~120M了
